/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentId = IDL.Nat;
export const Service = IDL.Variant({
  'HairConsultation' : IDL.Null,
  'SkinConsultation' : IDL.Null,
  'SkinTreatment' : IDL.Null,
  'Other' : IDL.Null,
  'HairTransplant' : IDL.Null,
  'HairTreatment' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'service' : Service,
  'status' : AppointmentStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const AppointmentRequest = IDL.Record({
  'service' : Service,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAppointment' : IDL.Func(
      [AppointmentId],
      [IDL.Opt(Appointment)],
      ['query'],
    ),
  'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'submitAppointment' : IDL.Func([AppointmentRequest], [Appointment], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentId = IDL.Nat;
  const Service = IDL.Variant({
    'HairConsultation' : IDL.Null,
    'SkinConsultation' : IDL.Null,
    'SkinTreatment' : IDL.Null,
    'Other' : IDL.Null,
    'HairTransplant' : IDL.Null,
    'HairTreatment' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'service' : Service,
    'status' : AppointmentStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AppointmentRequest = IDL.Record({
    'service' : Service,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAppointment' : IDL.Func(
        [AppointmentId],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'submitAppointment' : IDL.Func([AppointmentRequest], [Appointment], []),
  });
};

export const init = ({ IDL }) => { return []; };