/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface AppointmentRequest {
    service: Service;
    name: string;
    email: string;
    message: string;
    phone: string;
}
export type AppointmentId = bigint;
export interface Appointment {
    id: AppointmentId;
    service: Service;
    status: AppointmentStatus;
    name: string;
    createdAt: Timestamp;
    email: string;
    message: string;
    phone: string;
}
export enum AppointmentStatus {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum Service {
    HairConsultation = "HairConsultation",
    SkinConsultation = "SkinConsultation",
    SkinTreatment = "SkinTreatment",
    Other = "Other",
    HairTransplant = "HairTransplant",
    HairTreatment = "HairTreatment"
}
export interface backendInterface {
    getAppointment(id: AppointmentId): Promise<Appointment | null>;
    listAppointments(): Promise<Array<Appointment>>;
    submitAppointment(req: AppointmentRequest): Promise<Appointment>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentRequest as _AppointmentRequest, AppointmentStatus as _AppointmentStatus, Service as _Service, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAppointment(arg0: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAppointment(arg0: AppointmentRequest): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(to_candid_AppointmentRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Appointment_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(to_candid_AppointmentRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Appointment_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    service: _Service;
    status: _AppointmentStatus;
    name: string;
    createdAt: _Timestamp;
    email: string;
    message: string;
    phone: string;
}): {
    id: AppointmentId;
    service: Service;
    status: AppointmentStatus;
    name: string;
    createdAt: Timestamp;
    email: string;
    message: string;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_Service_n4(_uploadFile, _downloadFile, value.service),
        status: from_candid_AppointmentStatus_n6(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HairConsultation: null;
} | {
    SkinConsultation: null;
} | {
    SkinTreatment: null;
} | {
    Other: null;
} | {
    HairTransplant: null;
} | {
    HairTreatment: null;
}): Service {
    return "HairConsultation" in value ? Service.HairConsultation : "SkinConsultation" in value ? Service.SkinConsultation : "SkinTreatment" in value ? Service.SkinTreatment : "Other" in value ? Service.Other : "HairTransplant" in value ? Service.HairTransplant : "HairTreatment" in value ? Service.HairTreatment : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): AppointmentStatus {
    return "Confirmed" in value ? AppointmentStatus.Confirmed : "Cancelled" in value ? AppointmentStatus.Cancelled : "Pending" in value ? AppointmentStatus.Pending : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentRequest): _AppointmentRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: Service;
    name: string;
    email: string;
    message: string;
    phone: string;
}): {
    service: _Service;
    name: string;
    email: string;
    message: string;
    phone: string;
} {
    return {
        service: to_candid_Service_n11(_uploadFile, _downloadFile, value.service),
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): {
    HairConsultation: null;
} | {
    SkinConsultation: null;
} | {
    SkinTreatment: null;
} | {
    Other: null;
} | {
    HairTransplant: null;
} | {
    HairTreatment: null;
} {
    return value == Service.HairConsultation ? {
        HairConsultation: null
    } : value == Service.SkinConsultation ? {
        SkinConsultation: null
    } : value == Service.SkinTreatment ? {
        SkinTreatment: null
    } : value == Service.Other ? {
        Other: null
    } : value == Service.HairTransplant ? {
        HairTransplant: null
    } : value == Service.HairTreatment ? {
        HairTreatment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
